[package]
name = "call"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.22", features = ["json", "rustls-tls"] }
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
